// Generated by j.chamois
'use strict';

module.exports = function (grunt) {

    // charge les tache grunt en auto
    require('load-grunt-tasks')(grunt);

    // sors le temps que prennent les taches grunt (pour éventuelles opti)
    require('time-grunt')(grunt);

    // Config des taches
    grunt.initConfig({

        
        yeoman: {
            // chemin dossier projet
            app: 'app',
            dist: 'dist',
            img:'img',
            css : 'css',
            js :'js'
        },



        // Vide les rep précédemment remplit
        clean: {
            dist: {
                files: [{
                    dot: true,
                    src: [
                        '.tmp',
                        '<%= yeoman.dist %>/*',
                        '!<%= yeoman.dist %>/.git*'
                    ]
                }]
            } 
        },

        // cache busting via rename des fichiers
        rev: {
            dist: {
                files: {
                    src: [
                        '<%= yeoman.dist %>/<%= yeoman.js %>/{,*/}*.js',
                        '<%= yeoman.dist %>/<%= yeoman.css %>/{,*/}*.css',
                        '<%= yeoman.dist %>/<%= yeoman.img %>/{,*/}*.{gif,jpeg,jpg,png,webp}',
                        '<%= yeoman.dist %>/<%= yeoman.css %>/fonts/{,*/}*.*'
                    ]
                }
            }
        },

        // parse le HTML pour utiliser les usemin block pour concat, minif automatique. 

        useminPrepare: {
            options: {
                dest: '<%= yeoman.dist %>'
            },
            html: '<%= yeoman.app %>/index.php'
        },

        // rewrite des fichiers

        usemin: {
            options: {
                assetsDirs: ['<%= yeoman.dist %>']
            },
            html: ['<%= yeoman.dist %>/{,*/}*.php'],
            css: ['<%= yeoman.dist %>/<%= yeoman.css %>/{,*/}*.css']
        },

        // Minif des img
        imagemin: {
            dist: {
                files: [{
                    expand: true,
                    cwd: '<%= yeoman.app %>/<%= yeoman.img %>',
                    src: '{,*/}*.{gif,jpeg,jpg,png}',
                    dest: '<%= yeoman.dist %>/<%= yeoman.img %>'
                }]
            }
        },
        // Minif html
        htmlmin: {
            dist: {
                options: {
                    collapseBooleanAttributes: true,
                    collapseWhitespace: false,
                    removeAttributeQuotes: true,
                    removeCommentsFromCDATA: true,
                    removeEmptyAttributes: true,
                    removeOptionalTags: true,
                    removeRedundantAttributes: true,
                    useShortDoctype: true
                },
                files: [{
                    expand: true,
                    cwd: '<%= yeoman.dist %>',
                    src: '{,*/}*.php',
                    dest: '<%= yeoman.dist %>'
                }]
            }
        },

        // Copie des fichiers non process dans dist
        copy: {
            dist: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= yeoman.app %>',
                    dest: '<%= yeoman.dist %>',
                    src: [
                        '*.{ico,png,txt}',
                        '.htaccess',
                        '<%= yeoman.img %>/{,*/}*.webp',
                        '{,*/}*.php',
                        '<%= yeoman.css %>/fonts/{,*/}*.*',
                        '<%= yeoman.js %>/modernizr/*'
                    ]
                }]
            },
            css: {
                expand: true,
                dot: true,
                cwd: '<%= yeoman.app %>/<%= yeoman.css %>',
                dest: '.tmp/<%= yeoman.css %>/',
                src: '{,*/}*.css'
            }
        },

        // Effectue des taches en parallele: nodejs la puisseeeeince !
        concurrent: {
            dist: [
                'copy:css',
                'imagemin'  
            ]
        }
 
    });

// ajouter le watch

    grunt.registerTask('default', [
        'clean:dist',
        'useminPrepare',
        'concurrent:dist',
        'concat',
        'cssmin',
        'uglify',
        'copy:dist',
        'rev',
        'usemin',
        'htmlmin'
    ]);
   
};
